spring:
  mvc:
#    静态资源前缀
    static-path-pattern: /res/**
    #    时间格式化
    format:
      date: yyyy-MM-dd
      date-time: yyyy-MM-dd HH:mm:ss
      time: HH:mm:ss
  profiles:
    active: #

sa-token:
  token-name: token

moore-core:
  aop:
    log-print-exclude-pattern: [password,pass]
    interceptor-path-pattern:
      - /**
    exclude-path-pattern:
      - /test/login

#  mail:
#    from: 111
#    to: 11,22
#    cc: 44
#    port: 333
#    user: admin
#    password: 123
#    host: smtp.163.com
#    encoding: UTF-8



logging:
  config: classpath:logback.xml
  level:
    root: info
